name: preview_on_dispatch

on: workflow_dispatch

concurrency:
  group: ci-preview-${{ github.event.ref }}
  cancel-in-progress: true

jobs:
  preview_backend:
    uses: jalantechnologies/platform-github/.github/workflows/kube.yml@v2.5
    with:
      app_name: website-backend
      app_env: preview
      app_hostname: '{1}-website-backend.preview.getsunlead.com'
      branch: ${{ github.event.ref }}
      build_context: 'api'
      build_args: |
        CI=true
        NODE_ENV=production
      deploy_root: 'lib/kube/backend'
      steps: 'deploy'
    secrets:
      docker_registry: docker-registry.getsunlead.com/website
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      doppler_token: ${{ secrets.DOPPLER_PREVIEW_TOKEN }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      do_cluster_id: ${{ secrets.DO_CLUSTER_ID }}

  preview_frontend:
    uses: jalantechnologies/platform-github/.github/workflows/kube.yml@v2.5
    needs: 'preview_backend'
    with:
      app_name: website-frontend
      app_env: preview
      app_hostname: '{1}-website.preview.getsunlead.com'
      branch: ${{ github.event.ref }}
      build_args: |
        CI=true
        NODE_ENV=production
        STRAPI_API_URL=${{ needs.preview_backend.outputs.deploy_url }}
        STRAPI_TOKEN=113b768e778c07b1e24eb9b8bea3076139a01945dec8082aa3c051e245640f6fa936cbf4f75469bd5ec7724edd597243912ee68c86c0d6e02c596ced0f862627aa586d259b7769842fa85cb7ccf3426126455ccd3d582f825b52d803f72f688cdae6f5696455edd3e99b680a5a08b9e8e13a594adf26a79e4d758fc34b1e8706
      deploy_root: 'lib/kube/frontend'
      steps: 'deploy'
    secrets:
      docker_registry: docker-registry.getsunlead.com/website
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      do_cluster_id: ${{ secrets.DO_CLUSTER_ID }}
